name: swex
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiobotocore=2.5.0
  - aiohttp=3.8.5
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - alsa-lib=1.2.10
  - aom=3.5.0
  - asciitree=0.3.3
  - asttokens=2.2.1
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.5
  - bokeh=3.3.1
  - boost-cpp=1.78.0
  - botocore=1.29.76
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cartopy=0.22.0
  - cdsapi=0.7.5
  - certifi=2025.1.31
  - cf_xarray=0.8.6
  - cffi=1.15.1
  - cfgrib=0.9.10.4
  - cfitsio=4.3.1
  - cftime=1.6.2
  - charset-normalizer=3.2.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.4
  - contourpy=1.1.0
  - cryptography=41.0.3
  - curl=8.8.0
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2025.2.0
  - dask-core=2025.2.0
  - datapi=0.1.2
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.8
  - decorator=5.1.1
  - distributed=2025.2.0
  - docrep=0.3.2
  - docutils=0.20.1
  - donfig=0.8.1.post0
  - eccodes=2.31.0
  - esmf=8.4.2
  - esmpy=8.4.2
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fasteners=0.17.3
  - ffmpeg=6.0.0
  - fftw=3.3.10
  - findlibs=0.0.5
  - fiona=1.9.4
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - future=0.18.3
  - gdal=3.7.3
  - gdk-pixbuf=2.42.10
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - ghostscript=10.02.1
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - glog=0.7.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - goes2go=2023.8.0
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - gtk2=2.24.33
  - gts=0.7.6
  - h5netcdf=1.5.0
  - h5py=3.9.0
  - harfbuzz=8.2.1
  - hdf4=4.2.15
  - hdf5=1.14.2
  - herbie-data=2023.3.0
  - icu=73.2
  - idna=3.4
  - imagemagick=7.1.1_28
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.1
  - ipympl=0.9.3
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - jasper=4.1.0
  - jbig=2.1
  - jedi=0.19.0
  - jinja2=3.1.2
  - jmespath=0.10.0
  - joblib=1.3.2
  - json-c=0.17
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyterlab_widgets=3.0.9
  - kealib=1.5.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.0.6
  - libarchive=3.7.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.8.0
  - libdeflate=1.19
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgdal=3.7.3
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.78.3
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.47
  - libgrpc=1.62.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpciaccess=0.17
  - libpng=1.6.42
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.56.3
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.19.0
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.6.0
  - libxml2=2.12.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - metpy=1.5.1
  - minizip=4.0.2
  - mpg123=1.31.3
  - msgpack-python=1.0.7
  - multidict=6.0.4
  - multiurl=0.3.3
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf-fortran=4.6.1
  - netcdf4=1.6.4
  - nettle=3.8.1
  - networkx=3.1
  - nspr=4.35
  - nss=3.97
  - numba=0.58.1
  - numcodecs=0.12.1
  - numpy=1.25.2
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openpyxl=3.1.4
  - openssl=3.4.1
  - orc=2.0.1
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.1.0
  - pango=1.50.14
  - param=2.0.1
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.42
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pint=0.22
  - pip=23.2.1
  - pixman=0.42.2
  - pkg-config=0.29.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - polars=1.24.0
  - pooch=1.7.0
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.3.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pycrs=1.0.2
  - pyct=0.5.0
  - pygments=2.16.1
  - pygrib=2.1.4
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-eccodes=1.6.0
  - python-fastjsonschema=2.19.0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - rasterio=1.3.9
  - rdma-core=28.9
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.32.0
  - requests=2.31.0
  - rioxarray=0.15.0
  - rpds-py=0.13.2
  - rtree=1.0.1
  - s2n=1.4.15
  - s3fs=2023.6.0
  - salem=0.3.11
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=68.1.2
  - shapely=2.0.2
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sparse=0.15.1
  - sqlite=3.45.1
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - svt-av1=1.7.0
  - synopticpy=2024.12.0
  - tblib=2.0.0
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzcode=2023c
  - tzdata=2023c
  - ucx=1.14.1
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - wrapt=1.15.0
  - wrf-python=1.3.4.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.1.2
  - xarray-einstats=0.7.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xesmf=0.8.2
  - xgcm=0.8.1
  - xkeyboard-config=2.39
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xrft=1.0.1
  - xwrf=0.0.2
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.18.2
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - imageio==2.33.1
      - lazy-loader==0.3
      - ridge-map==0.0.4
      - scikit-image==0.22.0
      - srtm-py==0.3.7
      - tifffile==2023.12.9